services:
  - type: web
    name: supreme-vc-music-bot
    runtime: docker
    plan: free

    autoDeploy: true

    envVars:
      - key: API_ID
        sync: false

      - key: API_HASH
        sync: false

      - key: BOT_TOKEN
        sync: false

      - key: STRING_SESSION
        sync: false

      - key: MONGO_DB_URI
        sync: false

      - key: REDIS_URI
        sync: false

      - key: OWNER_ID
        sync: false

      - key: LOG_GROUP_ID
        sync: false

      - key: SUPPORT_GROUP
        sync: false

      - key: SUPPORT_CHANNEL
        sync: false

      - key: BOT_NAME
        value: Supreme VC Music Bot

      - key: MAX_QUALITY
        value: high

      - key: AUTO_LEAVE
        value: "3600"

      - key: AUTO_RESTART
        value: "True"

      - key: YT_COOKIES_PATH
        value: cookies.txt
